# @package agent
_target_: agent.gaifo.GAIfOAgent
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
device: ${device}
lr: 1e-4
critic_target_tau: 0.005
update_policy_freq: 1
update_every_steps: 2
use_tb: ${use_tb}
num_expl_steps: 2000
hidden_dim: ${suite.hidden_dim}
feature_dim: 50
stddev_schedule: 0.1
expl_noise: 0.4  # 'linear(1.0,0.1,500000)'
stddev_clip: 0.3
augment: True
use_actions: false
suite_name: ${suite.name}
obs_type: ${obs_type}
name: 'gaifo'